version: '2'
services:
  trezor-user-env-unix:
    image: registry.gitlab.com/satoshilabs/trezor/trezor-user-env/trezor-user-env
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - LOCAL_USER_ID=$LOCAL_USER_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  connect-explorer-dev:
    container_name: connect-explorer-dev
    extends:
      service: suite-base
      file: docker-compose.suite-base.yml
      # todo: we are going to dockerize connect and run it as another localhost service later
    command: bash -c "TREZOR_CONNECT_SRC=https://connect.trezor.io/8/ yarn workspace @trezor/connect-explorer dev"
    network_mode: service:trezor-user-env-unix

  test-open:
    build:
      context: .
      dockerfile: ./puppeteer/Dockerfile
    container_name: test-runner
    ipc: host
    depends_on:
      - trezor-user-env-unix
      - connect-explorer-dev
    network_mode: service:trezor-user-env-unix
    environment:
      - LOCAL_USER_ID=$LOCAL_USER_ID
      - DISPLAY=$DISPLAY
      - HEADLESS=false
    working_dir: /e2e
    command: bash -c "Xvfb :10 -ac & node ./packages/integration-tests/projects/connect-popup/index.js"
    volumes:
      - ../:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
